#!/bin/bash

#set -x

JOB_ID=$1
shift

mkdir OUTPUT

# do we have files from a previous run?
cp -r $JOB_ID/* OUTPUT/

# Check if the job is a restart
LAST_LOG=`ls OUTPUT/gce-log-*.dat | sort | tail -n 1`
if [ "x$LAST_LOG" != "x" ]; then
    echo "Restarting a previous run"
    # Loop through all log files in OUTPUT
    for logfile in $(ls OUTPUT/gce-log*.dat); do
	# Grab the restart command from the log file
        CMD=`cat $logfile | grep pimc.e | sed 's/# //'`
        echo "Command is: $CMD" 1>&2
	# Grab PIMCID from log file
        PIMCID=`cat $logfile | grep PIMCID | sed 's/# //'`
        echo "$PIMCID" 1>&2
	# Get line containing bin count from the stdout file
        binline=`grep -R "$PIMCID" OUTPUT/*.out | tail -n 2 | head -n 1`
        echo "Line with bin count from .out file is: $binline" 1>&2
	# Get the bin count
        re="Bin # *([0-9]*)"
        if [[ $binline =~ $re ]]; then
            bincount="${BASH_REMATCH[1]}"
            echo "Bins collected: $bincount" 1>&2
        fi
        binmatch="-S ([0-9]*)"
	# Get the original bin request from log file
        if [[ $CMD =~ $binmatch ]]; then
            binrequest="${BASH_REMATCH[1]}"
            echo "Bins requested: $binrequest" 1>&2
        fi
	# Adjust the bin count and rewrite command
        adjustedbins=$((binrequest-bincount))
        echo "Adjusted bin request: $adjustedbins" 1>&2
        NEWCMD=`echo $CMD | sed "s/-S [0-9]*/-S $adjustedbins/"`
        echo "Adjusted command: $NEWCMD" 1>&2
	# Replace command string in log file for future restarts
	sed -i "s/-S $binrequest/-S $adjustedbins/g" $logfile
	# Execute command and send output to .out file in OUTPUT
	$NEWCMD | tee OUTPUT/pimc.out
    done
else
    ./pimc.e "$@" | tee OUTPUT/pimc.out 
fi
EXIT_CODE=$?

cp -r OUTPUT/* $JOB_ID/

exit $EXIT_CODE

